apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-worker
  template:
    metadata:
      labels:
        app: backend-worker
    spec:
      containers:
      - name: worker
        image: vote-backend:latest
        imagePullPolicy: Never 