apiVersion: apps/v1
kind: deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-ui
        image: vote-frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: service
metadata:
  name: frontend
spec:
  type: Nodeport
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31000
  selector:
    app: frontend